import { getProductImages } from './placeholderImages.js'

/**
 * 测试数据集 - 用于快速走通全流程
 */

// 单个商品测试数据（用于"添加商品"页面一键填充）
export const singleTestProduct = {
  name: '夏季冰感防晒衣 UPF50+',
  category: '女装',
  brand: 'CoolSkin',
  material: '冰丝锦纶',
  size: 'S-XXL',
  colors: ['奶白色', '浅蓝色', '薄荷绿', '浅粉色'],
  audience: '女性',
  sellingPoints: [
    'UPF50+ 专业防晒',
    '冰感面料 体感降温3°C',
    '轻薄透气仅89g',
    'A类母婴级面料',
    '便携可折叠收纳',
  ],
  price: '128',
  platforms: ['淘宝', '抖音'],
  images: getProductImages('shoes'),
  refImages: getProductImages('bag').slice(0, 1),
  refUrl: 'https://example.com/reference-product',
  saveToAssets: true,
  notes: '主打夏季防晒场景，强调冰感和轻薄',
}

// 批量导入测试数据（模拟 Excel 解析结果）
export const batchTestProducts = [
  {
    name: '复古牛仔阔腿裤 高腰显瘦',
    category: '女装',
    brand: 'DenimLab',
    material: '纯棉牛仔',
    size: 'XS-XL',
    audience: '女性',
    price: 159,
    platforms: ['淘宝', '拼多多'],
    sellingPoints: ['高腰设计显腿长', '纯棉不闷热', '复古水洗工艺'],
    colors: ['深蓝', '浅蓝', '黑色'],
    _rowIndex: 1,
    _errors: [],
  },
  {
    name: '男士商务休闲皮鞋 真皮软底',
    category: '鞋靴',
    brand: 'GentleStep',
    material: '头层牛皮',
    size: '38-44',
    audience: '男性',
    price: 329,
    platforms: ['京东', '淘宝'],
    sellingPoints: ['头层牛皮', '软底减震', '商务百搭'],
    colors: ['黑色', '棕色'],
    _rowIndex: 2,
    _errors: [],
  },
  {
    name: '便携式颈挂风扇 USB充电',
    category: '数码',
    brand: 'BreezePro',
    material: 'ABS+硅胶',
    size: '挂脖式',
    audience: '通用',
    price: 69,
    platforms: ['拼多多', '抖音'],
    sellingPoints: ['3档风速调节', '8小时续航', '静音低于30dB', '仅120g'],
    colors: ['白色', '粉色', '黑色'],
    _rowIndex: 3,
    _errors: [],
  },
  {
    name: '儿童防蚊裤 纯棉薄款',
    category: '其他',
    brand: 'BabyComfy',
    material: '纯棉',
    size: '90-140cm',
    audience: '儿童',
    price: 49,
    platforms: ['淘宝', '拼多多', '抖音'],
    sellingPoints: ['物理防蚊面料', 'A类婴幼儿标准', '松紧腰不勒肚'],
    colors: ['浅灰', '浅绿', '浅蓝'],
    _rowIndex: 4,
    _errors: [],
  },
  {
    name: '日式简约陶瓷马克杯 大容量',
    category: '家居',
    brand: 'MujiStyle',
    material: '高温陶瓷',
    size: '400ml',
    audience: '通用',
    price: 39,
    platforms: ['淘宝', '京东'],
    sellingPoints: ['高温烧制不含铅', '大容量400ml', '哑光质感手感好'],
    colors: ['米白', '浅灰', '墨绿'],
    _rowIndex: 5,
    _errors: [],
  },
]
